<a href="https://colab.research.google.com/github/AliUrbina/Data_Science_Projects/blob/main/Styling_charts_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##**Let's give our tables some style using Python!**

####Objective: Generate insights from a 2016–2019 sales dataset for a major online department store in Argentina, and create visualizations to share key findings with other departments.

###**Preparation of the data**

In [1]:
import pandas as pd

print(pd.__version__)

2.2.2

In [2]:
sales = pd.read_csv('https://gist.githubusercontent.com/ahcamachod/d2efadda3f3833d65da750c64705ac42/raw/80aef6f3bad210d34b67ed85565f039a30e2d9e0/ventas.csv', sep='#')
sales.head()

,fecha_pedido,fecha_envio,modo_envio,nombre_cliente,segmento_cliente,ciudad,provincia,region,departamento,tipo_producto,precio_base,precio_unit_sin_descuento,descuento,precio_unit_venta,cantidad,ventas,ganancia
0,2018-11-09,2018-11-12,Económica,Gaspar Fernández,B2C,Lomas de Zamora,Buenos Aires,Buenos Aires,Materiales de construcción,Fontanería,409.70,445.33,0.000,445.33,2,890.66,71.26
1,2018-11-09,2018-11-12,Económica,Gaspar Fernández,B2C,Lomas de Zamora,Buenos Aires,Buenos Aires,Materiales de construcción,Herramientas,705.10,829.53,0.000,829.53,3,2488.59,373.29
2,2018-06-13,2018-06-17,Económica,Matías González,B2B,Córdoba,Córdoba,Central,Jardinería y paisajismo,Semillas,19.02,24.86,0.000,24.86,2,49.72,11.68
3,2017-10-12,2017-10-19,Entrega estándar,Lucas González,B2C,Gualeguay,Entre Ríos,Litoral,Materiales de construcción,Materiales de revestimiento,781.38,840.19,0.225,651.15,5,3255.75,-651.15
4,2017-10-12,2017-10-19,Entrega estándar,Lucas González,B2C,Gualeguay,Entre Ríos,Litoral,Jardinería y paisajismo,Macetas,35.88,42.24,0.100,38.02,2,76.04,4.28

In [3]:
sales = sales[['fecha_pedido', 'modo_envio','nombre_cliente', 'segmento_cliente', 'ciudad',
              'provincia', 'region', 'departamento', 'tipo_producto',
              'ventas', 'cantidad', 'ganancia']]
sales.head(2)

,fecha_pedido,modo_envio,nombre_cliente,segmento_cliente,ciudad,provincia,region,departamento,tipo_producto,ventas,cantidad,ganancia
0,2018-11-09,Económica,Gaspar Fernández,B2C,Lomas de Zamora,Buenos Aires,Buenos Aires,Materiales de construcción,Fontanería,890.66,2,71.26
1,2018-11-09,Económica,Gaspar Fernández,B2C,Lomas de Zamora,Buenos Aires,Buenos Aires,Materiales de construcción,Herramientas,2488.59,3,373.29

In [4]:
sales.shape

(8940, 12)

In [5]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8940 entries, 0 to 8939
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   fecha_pedido      8940 non-null   object
 1   modo_envio        8940 non-null   object
 2   nombre_cliente    8940 non-null   object
 3   segmento_cliente  8940 non-null   object
 4   ciudad            8940 non-null   object
 5   provincia         8940 non-null   object
 6   region            8940 non-null   object
 7   departamento      8940 non-null   object
 8   tipo_producto     8940 non-null   object
 9   ventas            8940 non-null   float64
 10  cantidad          8940 non-null   int64
 11  ganancia          8940 non-null   float64
dtypes: float64(2), int64(1), object(9)
memory usage: 838.3+ KB

####We only need to transform the date, as it's currently marked as an "object" but should be a datetime.

In [6]:
sales['fecha_pedido'] = pd.to_datetime(sales['fecha_pedido'],format='%Y-%m-%d')
sales.head(2)

,fecha_pedido,modo_envio,nombre_cliente,segmento_cliente,ciudad,provincia,region,departamento,tipo_producto,ventas,cantidad,ganancia
0,2018-11-09,Económica,Gaspar Fernández,B2C,Lomas de Zamora,Buenos Aires,Buenos Aires,Materiales de construcción,Fontanería,890.66,2,71.26
1,2018-11-09,Económica,Gaspar Fernández,B2C,Lomas de Zamora,Buenos Aires,Buenos Aires,Materiales de construcción,Herramientas,2488.59,3,373.29

In [7]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8940 entries, 0 to 8939
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   fecha_pedido      8940 non-null   datetime64[ns]
 1   modo_envio        8940 non-null   object
 2   nombre_cliente    8940 non-null   object
 3   segmento_cliente  8940 non-null   object
 4   ciudad            8940 non-null   object
 5   provincia         8940 non-null   object
 6   region            8940 non-null   object
 7   departamento      8940 non-null   object
 8   tipo_producto     8940 non-null   object
 9   ventas            8940 non-null   float64
 10  cantidad          8940 non-null   int64
 11  ganancia          8940 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(8)
memory usage: 838.3+ KB

####**Our DataFrame is now ready for analysis.**

###**Step 1: Identifying the top 10 clients.**

1. Let's create another dataframe named clients for this step.
2. with the nlargest function, python give us the 10 clients with more sales
3. since we want just a copy, we use the copy function
4. Reset index.

In [8]:

clients = sales.groupby(['nombre_cliente'])['ventas'].sum().nlargest(10).copy()
clients = clients.reset_index()
clients

      nombre_cliente    ventas
0    Víctor Carrasco  73370.61
1        Brisa Rojas  68868.11
2       Mateo Vargas  62749.75
3      Vicente Rojas  59544.11
4        Laura Rojas  51398.87
5         Lucía Díaz  48178.99
6   Cristina Barrios  47610.80
7  Alejandro Sánchez  43769.25
8      Pamela Huerta  42354.19
9     Carlos Sánchez  41238.81

In [9]:
clients.columns = ['Clients','Sales']
clients['Ranking'] = clients.index + 1
clients.set_index('Ranking', inplace = True)
clients

                   Clients     Sales
Ranking
1          Víctor Carrasco  73370.61
2              Brisa Rojas  68868.11
3             Mateo Vargas  62749.75
4            Vicente Rojas  59544.11
5              Laura Rojas  51398.87
6               Lucía Díaz  48178.99
7         Cristina Barrios  47610.80
8        Alejandro Sánchez  43769.25
9            Pamela Huerta  42354.19
10          Carlos Sánchez  41238.81

In [10]:
#Since the previous tables weren't stored in any DataFrame, we’re now
#saving them in one named "style".
style = clients.style
style

In [11]:
style.format({'Sales':'{:,.2f}'})
style

###**Step 2: Identifying the top products.**

In [12]:
high_sales = sales.groupby(['tipo_producto'])[['ventas', 'ganancia']].sum()

In [13]:
high_sales.index.name = 'tipo de producto'
high_sales

                                 ventas  ganancia
tipo de producto
Brotes                          8811.32   1381.42
Decoración de jardín           82680.08   9939.43
Equipos de limpieza           542304.58   8724.39
Fertilizantes                  53144.74  11254.88
Fontanería                    373223.88  -5622.34
Herramientas                  995158.41  41020.34
Herramientas automotrices     502109.29  63330.22
Herramientas de jardinería    648879.72  53202.88
Iluminación                   275229.53  20264.54
Macetas                       696044.18  33941.85
Materiales de paisajismo      150552.49  -1912.37
Materiales de revestimiento   629656.36 -28869.01
Muebles de exterior           328932.27  26784.59
Neumáticos                   1022428.97  67460.05
Pesticidas                    244956.04  53343.89
Piezas de repuesto            486907.94  91148.67
Semillas                       39979.75   8865.09

In [14]:
product_style = high_sales.style
product_style

In [15]:
product_style.format('USD {:,.2f}')

In [16]:
product_style = product_style.format('USD {:,.2f}').highlight_max(color='lightgreen').highlight_min(color='red')
product_style

In [17]:
product_style.background_gradient(cmap='Greens')

In [18]:
#Let's change the titles for our table, to make it look better.
#For this we need to install CSS, so let's call it.

titles = {
        'selector':'th',
        'props':'font-weight:bold; font-family:Arial; text-align:center; text-transform:capitalize'
}

In [19]:
product_style.set_table_styles([titles], overwrite=False)

##**Order distribution by region**

##**Where the majority of orders are concentrated within the country.**

In [20]:
region = pd.DataFrame(sales['region'].value_counts())
region.columns = ['N° Orders']
region.index.name = 'Region'
region

              N° Orders
Region
Buenos Aires       2822
Litoral            1924
Norte              1555
Central            1276
Cuyo                915
Patagónica          448

In [21]:
import numpy as np

In [22]:
percentage = region['N° Orders'].to_numpy()
percentage = 100*percentage/percentage.sum()
percentage

array([31.56599553, 21.5212528 , 17.39373602, 14.27293065, 10.23489933,
        5.01118568])

In [23]:
region['Orders Percentage'] = percentage
region

              N° Orders  Orders Percentage
Region
Buenos Aires       2822          31.565996
Litoral            1924          21.521253
Norte              1555          17.393736
Central            1276          14.272931
Cuyo                915          10.234899
Patagónica          448           5.011186

In [24]:
#Let's fix the style
region_style =region.style
region_style

In [25]:
#First headers and white table
headers = {
    'selector': 'th', #table head = th
    'props':'font-weight:bold; font-family:Arial; text-align:right; background-color: white;'
}

rows = {
    'selector': 'td',
    'props':'background-color: white;'
}

region_style.set_table_styles([headers,rows])

In [26]:
region_style.format({'Orders Percentage':'{:.2f} %'}).bar(subset='Orders Percentage', vmin=0,vmax=100,color='#9cd3bb')

##**Identify the pattern per month**

In [27]:
months = sales.copy()
months = months.sort_values('fecha_pedido')
months

,fecha_pedido,modo_envio,nombre_cliente,segmento_cliente,ciudad,provincia,region,departamento,tipo_producto,ventas,cantidad,ganancia
7171,2016-01-04,Entrega estándar,Ramiro Guzmán,B2C,Rosario,Santa Fe,Litoral,Jardinería y paisajismo,Pesticidas,55.92,2,9.44
651,2016-01-05,Entrega estándar,Jerónimo Cortés,B2B,Pergamino,Buenos Aires,Buenos Aires,Jardinería y paisajismo,Herramientas de jardinería,12.04,2,-9.32
650,2016-01-05,Entrega estándar,Jerónimo Cortés,B2B,Pergamino,Buenos Aires,Buenos Aires,Jardinería y paisajismo,Macetas,927.30,3,-110.13
649,2016-01-05,Entrega estándar,Jerónimo Cortés,B2B,Pergamino,Buenos Aires,Buenos Aires,Jardinería y paisajismo,Semillas,40.08,3,7.26
1576,2016-01-06,Entrega estándar,Florencia Chávez,B2C,Ciudad Autónoma de Buenos Aires,Ciudad Autónoma de Buenos Aires,Buenos Aires,Jardinería y paisajismo,Decoración de jardín,66.42,3,8.31
...,...,...,...,...,...,...,...,...,...,...,...,...
796,2019-12-31,Entrega estándar,Olivia Aguilar,B2C,La Plata,Buenos Aires,Buenos Aires,Jardinería y paisajismo,Herramientas de jardinería,179.43,3,33.63
795,2019-12-31,Entrega estándar,Olivia Aguilar,B2C,La Plata,Buenos Aires,Buenos Aires,Automotriz,Neumáticos,309.19,7,4.69
794,2019-12-31,Entrega estándar,Olivia Aguilar,B2C,La Plata,Buenos Aires,Buenos Aires,Materiales de construcción,Fontanería,1098.68,4,20.60
1151,2019-12-31,Entrega estándar,Francisco Cárdenas,B2B,Quilmes,Buenos Aires,Buenos Aires,Jardinería y paisajismo,Herramientas de jardinería,47.28,2,7.68
1152,2019-12-31,Entrega estándar,Francisco Cárdenas,B2B,Quilmes,Buenos Aires,Buenos Aires,Jardinería y paisajismo,Herramientas de jardinería,70.44,2,11.00

In [28]:
#take our df and create new attribute call month using string format time (strftime)

months['month'] = months['fecha_pedido'].dt.strftime('%Y - %b')
months = months.reset_index(drop=True)
months

,fecha_pedido,modo_envio,nombre_cliente,segmento_cliente,ciudad,provincia,region,departamento,tipo_producto,ventas,cantidad,ganancia,month
0,2016-01-04,Entrega estándar,Ramiro Guzmán,B2C,Rosario,Santa Fe,Litoral,Jardinería y paisajismo,Pesticidas,55.92,2,9.44,2016 - Jan
1,2016-01-05,Entrega estándar,Jerónimo Cortés,B2B,Pergamino,Buenos Aires,Buenos Aires,Jardinería y paisajismo,Herramientas de jardinería,12.04,2,-9.32,2016 - Jan
2,2016-01-05,Entrega estándar,Jerónimo Cortés,B2B,Pergamino,Buenos Aires,Buenos Aires,Jardinería y paisajismo,Macetas,927.30,3,-110.13,2016 - Jan
3,2016-01-05,Entrega estándar,Jerónimo Cortés,B2B,Pergamino,Buenos Aires,Buenos Aires,Jardinería y paisajismo,Semillas,40.08,3,7.26,2016 - Jan
4,2016-01-06,Entrega estándar,Florencia Chávez,B2C,Ciudad Autónoma de Buenos Aires,Ciudad Autónoma de Buenos Aires,Buenos Aires,Jardinería y paisajismo,Decoración de jardín,66.42,3,8.31,2016 - Jan
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8935,2019-12-31,Entrega estándar,Olivia Aguilar,B2C,La Plata,Buenos Aires,Buenos Aires,Jardinería y paisajismo,Herramientas de jardinería,179.43,3,33.63,2019 - Dec
8936,2019-12-31,Entrega estándar,Olivia Aguilar,B2C,La Plata,Buenos Aires,Buenos Aires,Automotriz,Neumáticos,309.19,7,4.69,2019 - Dec
8937,2019-12-31,Entrega estándar,Olivia Aguilar,B2C,La Plata,Buenos Aires,Buenos Aires,Materiales de construcción,Fontanería,1098.68,4,20.60,2019 - Dec
8938,2019-12-31,Entrega estándar,Francisco Cárdenas,B2B,Quilmes,Buenos Aires,Buenos Aires,Jardinería y paisajismo,Herramientas de jardinería,47.28,2,7.68,2019 - Dec
8939,2019-12-31,Entrega estándar,Francisco Cárdenas,B2B,Quilmes,Buenos Aires,Buenos Aires,Jardinería y paisajismo,Herramientas de jardinería,70.44,2,11.00,2019 - Dec

In [29]:
pd.set_option('display.max_columns', None)

In [30]:
months_sales = months.pivot_table(index=months.departamento, columns='month', values='cantidad', aggfunc='sum', sort=False)
months_sales

month,2016 - Jan,2016 - Feb,2016 - Mar,2016 - Apr,2016 - May,2016 - Jun,2016 - Jul,2016 - Aug,2016 - Sep,2016 - Oct,2016 - Nov,2016 - Dec,2017 - Jan,2017 - Feb,2017 - Mar,2017 - Apr,2017 - May,2017 - Jun,2017 - Jul,2017 - Aug,2017 - Sep,2017 - Oct,2017 - Nov,2017 - Dec,2018 - Jan,2018 - Feb,2018 - Mar,2018 - Apr,2018 - May,2018 - Jun,2018 - Jul,2018 - Aug,2018 - Sep,2018 - Oct,2018 - Nov,2018 - Dec,2019 - Jan,2019 - Feb,2019 - Mar,2019 - Apr,2019 - May,2019 - Jun,2019 - Jul,2019 - Aug,2019 - Sep,2019 - Oct,2019 - Nov,2019 - Dec
departamento,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Jardinería y paisajismo,161,87,277,323,270,273,348,339,549,276,716,525,97,131,278,271,269,321,268,322,663,260,746,628,190,177,260,338,463,473,413,380,757,402,727,770,361,205,458,415,542,490,423,561,929,617,946,989
Automotriz,45,20,46,107,81,83,91,95,154,85,236,154,55,44,74,111,94,59,88,117,180,100,179,235,59,49,112,72,124,118,117,123,181,103,253,189,109,63,167,87,150,170,168,136,280,205,331,252
Materiales de construcción,60,23,102,69,91,114,104,101,182,94,213,269,93,38,100,85,76,120,128,106,194,129,259,258,91,67,127,128,171,117,132,113,227,171,308,294,83,67,107,131,172,151,162,132,282,213,312,395

In [31]:
month_style = months_sales.style
month_style

In [32]:
month_style.set_sticky(axis='index')

using CSS let's modofy it for good

In [33]:
columns = {
    'selector':'.col_heading',
    'props':'font-weight:normal; font-family:Arial'
}

table = {
    'selector':'th,td',
    'props': 'text-align:left'
}

indixes = {
    'selector':'index_name',
    'props':'font-weight:bold; font-family:Arial ;text-align:right'
}

month_style.set_table_styles([columns, table, indixes], overwrite=False)

##**Performance Report**

In [34]:
#Let's create new dt to prepera the data
df_client = sales.pivot_table(index='segmento_cliente',columns='modo_envio',values='ventas',aggfunc='sum')
df_client

modo_envio,Económica,Entrega en 24 horas,Entrega estándar,Envío rápido
segmento_cliente,,,,
B2B,718461.22,217465.60,1884738.56,602049.40
B2C,729174.73,182531.47,2248283.69,498294.88

In [35]:
#total values for that we are gouing to creat total columns and total index
df_client['Total'] = df_client.sum(axis=1)
df_client.loc['Total'] = df_client.sum()
df_client

modo_envio,Económica,Entrega en 24 horas,Entrega estándar,Envío rápido,Total
segmento_cliente,,,,,
B2B,718461.22,217465.60,1884738.56,602049.40,3422714.78
B2C,729174.73,182531.47,2248283.69,498294.88,3658284.77
Total,1447635.95,399997.07,4133022.25,1100344.28,7080999.55

In [36]:
#let's create a new style
sales_client = df_client.style.format('{:,.2f}')
sales_client

In [37]:
#let's create our dictionary table

table2={
    'selector': 'td,th:not(.index_name)',
    'props':'font-weight:normal; font-family:Arial; text-align:center; background-color:white'
}

indixes2={
    'selector':'.index_name',
    'props':'font-weight:normal; font-style:italic; text-align:right; color:#696969'
}

sales_client.set_table_styles([table2,indixes2])

In [38]:
#let's make some lines for our table
sales_client.set_table_styles({
    'Total':[
        {
            'selector':'th',
            'props':'border-top: 2px solid #181818'
        },
         {
            'selector':'td',
            'props':'border-top: 2px solid #181818'
        }
    ],
    'B2B':[
        {
            'selector': 'th',
            'props':'border-top: 2px solid #181818'
        },
         {
            'selector': 'td',
            'props': 'border-top: 2px solid #181818'
        }
    ]
}, overwrite=False, axis=1)

**Which segment generates the highest returns?**

In [39]:
#let's create our own selector

sales_client.set_table_styles({
    'Total':[
        {
         'selector':'.true',
          'props':'background-color: #D8D8D8'
    }]
},overwrite=False,axis=0)

#let's built a new dataframe, if its true we are going to apply the last code
colors_column = pd.DataFrame(['false','true','false'], index=df_client['Total'].index, columns=['Total'])
sales_client.set_td_classes(colors_column)